linters:
  GroupedPropertyOrder:
    enabled: true

    # defaults: applied to all groups
    defaults:
      space_around: true
      max_no_space: 3

    # preferred style
    style:  grouped-smacss

    # whether CSS variables should go first, or be ignored
    css_variables_first: true

    # or a definition of your own. Note that this takes precedence over style
    groups:

    # whether you get extended hinting information in the output
    extended_hinting:  false
